// Problem
// A string is simply an ordered collection of symbols selected from some alphabet and formed into a word; the length of a string is the number of symbols that it contains.

// An example of a length 21 DNA string (whose alphabet contains the symbols 'A', 'C', 'G', and 'T') is "ATGCTTCAGAAAGGTCTTACG."

// Given: A DNA string s
//  of length at most 1000 nt.

// Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s
// .

// Sample Dataset
// AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC
// Sample Output
// 20 12 17 21

let dna = "AATAATGCTCTTCTGTGCCCCTCAGTTGTAGTGGTCATTACCTGGCCTAGAGACGTGGCCAGCCCACAGCATGATGCCCCAACGTGTAGTGCTGGCCGCACTGCTACAAGGCGTTCATGGCCATATATGGTTACACGGAGTCACAGTCGCGTTACCCACCGTGTGCGACCTCATAGAAGCAAGCAAAACACATGTGTAATTCTAAACTGTTTCAGTACCGCAGAAAATAATTGAATAGCCGTGATGCAGCCGCGACACTACCCTTTAGTACGACCGTGAGCACTGTCAGACCGCGCCCTGATCGTGTTGAGGTTAAGTGGTCACGGCCGCTTCAACGCTACACAGAGCTTAGATGATGGTTCACCCGGAACAGGGAGTATAGCGGAATTTGCTTCAAATGCTGGATATTGAACACATCATCTAACGGTTTCCCGCATATTACCAGTAACGGCTCGTATCAATTCCCCAACGCCAACCGCGGCTTACAGTTAGCGAAGAAAGTCAATGTGGATGGCATCTGAGCCCACCTTCGCATTCAAAAACCACCGTTTCAGTAAGACGTGTCAGACGGGGAGCCCGAGCATTCAGCATCCGGCTGGATTGAGCCGTGCGCGGTAAGGTGAGAACGTCCGCCCACTCACAGTGGTGGCAAAGGATCCCGAACCTAACAGGTACTGATTAACGCCTTCACACGATTATGCCCAAGTATCCTCAAACCCTCACTTGTATGGACATATCTTCAGAAGCTAGAGAGGCAACATGTCACGTGGAAGCCGACGGGCTAGTCTGTACCCGAACCATCTGCCCACCTAGAGAACATATATCTACTCAGGTTGGACGGTAGTGTGCCTTACGTAGGAATTCGCGGAACATAGGCCGTCGACTGACTTAATTGAATTATGAGCGCGTTCCGAATTACCACCGGGCCTACATCGACAGCGCCCTGGGCTGGGCTGGGCA"

A_count = 0;
T_count = 0;
G_count = 0;
C_count = 0;

for (let i = 0; i < dna.length; i++) {
    if (dna[i] === "A") {
        A_count ++;
    }
    if (dna[i] === "T") {
        T_count ++;
    }
    if (dna[i] === "G") {
        G_count ++;
    }
    if (dna[i] === "C") {
        C_count ++;
    }
}

console.log(A_count + " " +  T_count + " " + G_count + " " + C_count);